# site

name: "hteaml"
subname: "programming without coffee"
description: "The journal of a British web designer and developer, who refuses to board the developers-drink-coffee bandwaggon. I write about the events of my life, and perhaps programming sometimes too."

url: "https://blieque.github.io"

# build

repository: "blieque/blieque.github.io"

paginate: 6
paginate_path: "page-:num/"

markdown: rdiscount
permalink: /:categories/:year/:month/:title

exclude: [ 'README.md', 'LICENSE.md', 'Gemfile.lock', 'Gemfile' ]

compress_html:
    clippings: all
