name: "Programming with Tea"
description: "The journal of a young British web designer and developer, who refuses to board the developers-drink-coffee bandwaggon."

url: "https://blieque.github.io"

paginate: 10
paginate_path: "blog/page-:num/"

markdown: rdiscount
permalink: pretty

exclude: [ 'README.md', 'LICENSE.md', 'Gemfile.lock', 'Gemfile' ]
